@baseUrl = http://localhost:3000/api
# categories
# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name":"rugs"
}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/zAx2hVd
Content-Type: application/json

{
    "name":"scraves"
}

###

# @name removeCategory
DELETE {{baseUrl}}/categories/zAx2hVd
Content-Type: application/json

